packages:
    - "apps/*"
    - "packages/*"

allowBuilds:
    "@firebase/util": false
    core-js: false
    esbuild: false
    protobufjs: false
    sharp: false
    unrs-resolver: false

overrides:
    esbuild: 0.25.12
