import { env } from "./env"

/**
 * Verify Access Token generated by MSG91 Login with OTP Widget on the frontend.
 * Endpoint: POST https://control.msg91.com/api/v5/widget/verifyAccessToken
 * @param accessToken The JWT / access-token received from the MSG91 widget success callback
 */
export const msg91VerifyAccessToken = async (accessToken: string) => {
    const res = await fetch("https://control.msg91.com/api/v5/widget/verifyAccessToken", {
        method: "POST",
        headers: {
            "Content-Type": "application/json",
            Accept: "application/json",
        },
        body: JSON.stringify({
            authkey: env.MSG91_AUTH_KEY,
            "access-token": accessToken,
        }),
    })

    const data: any = await res.json()
    if (data.type === "error" || data.status === "error") {
        throw new Error(data.message || "MSG91: Access token verification failed")
    }
    return data
}
